/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JSpgLib */

#ifndef _Included_JSpgLib
#define _Included_JSpgLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JSpgLib
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JSpgLib_printHello
  (JNIEnv *, jobject);

/*
 * Class:     JSpgLib
 * Method:    getPrimitive
 * Signature: ([[D)V
 */
JNIEXPORT void JNICALL Java_JSpgLib_getPrimitive
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
